CREATE OR REPLACE PACKAGE PKG_PROC_MULTAS AS


V_ANIO_REPORTE NUMBER(4):=2024;

PROCEDURE obtener_pagos_pacientes(V_ANIO_REPORTE IN NUMBER);

END PKG_PROC_MULTAS;




CREATE OR REPLACE PACKAGE BODY PKG_PROC_MULTAS IS

    
PROCEDURE obtener_pagos_pacientes (V_ANIO_REPORTE IN NUMBER) IS 

V_MONTO_A_PAGAR NUMBER(10):=0;
V_EDAD NUMBER(3):=0;
    -- SE INICIA UN CURSOR PARA OBTENER LOS DATOS DEL PACIENTE RELACIONANDOLOS CON UNA ATENCION Y SUS DATOS ASOCIADOS
       CURSOR C_PAGO IS      
            
            SELECT PR.PAC_RUN RUT,
            PR.DV_RUN RUTDV,  
            PR.pnombre || ' ' || PR.SNOMBRE || ' ' || PR.APATERNO|| ' ' || PR.AMATERNO NOMBRE_COMPLETO,
            AT.ATE_ID ID_ATENCION,
            PG.FECHA_VENC_PAGO FECHA_VENC,
            PG.FECHA_PAGO FECHA_PAGO,
            (PG.FECHA_PAGO - PG.FECHA_VENC_PAGO )DIAS_MOROSIDAD,
            ES.NOMBRE NOMRE_ESP,
            ES.ATE_ID ID_ESPECIALIDAD,
            PG.VALOR_A_PAGAR MONTO_CONSULTA,
            PR.FECHA_NACIMIENTO FECHA_NC
            FROM PACIENTE PR
            INNER JOIN ATENCION AT ON PR.PAC_RUN = AT.PAC_RUN
            INNER JOIN PAGO_ATENCION PG ON AT.ATE_ID = PG.ATE_ID
            INNER JOIN MEDICO MD ON AT.MED_RUN = MD.MED_RUN
            INNER JOIN ESPECIALIDAD ES ON ES.ESP_ID = MD.ESP_ID
            WHERE EXTRACT(YEAR FROM TO_DATE(PG.FECHA_PAGO, 'DD-MM-YY')) = V_ANIO_REPORTE; -- PERMITE TRAER LOS REGISTRO DEL AÑÑO SOLICITADO Y SETEADO EN LA VARIABLE
    
BEGIN
-- COMIENZA A RECORRER EL CURSOR 
  FOR  R_PAGO IN C_PAGO LOOP
            -- SI LOS DIAS DE MORA SON MAYORES QUE 0 SE DEBE COBRAR MULTA DE ACUERDO A LA ESPECIALIDAD
            IF R_PAGO.DIAS_MOROSIDAD > 0 THEN
        
                    IF R_PAGO.ID_ESPECIALIDAD = 100 THEN
                        V_MONTO_A_PAGAR:= R_PAGO.MONTO_CONSULTA + (1300 * R_PAGO.DIAS_MOROSIDAD );
                
                    ELSIF R_PAGO.ID_ESPECIALIDAD = 200 THEN
                     V_MONTO_A_PAGAR:= R_PAGO.MONTO_CONSULTA + (2000 * R_PAGO.DIAS_MOROSIDAD);
                           
                    ELSIF R_PAGO.ID_ESPECIALIDAD = 300 THEN
                         V_MONTO_A_PAGAR := R_PAGO.MONTO_CONSULTA + (1700 * R_PAGO.DIAS_MOROSIDAD);
        
                    ELSIF R_PAGO.ID_ESPECIALIDAD = 400 THEN
                         V_MONTO_A_PAGAR := R_PAGO.MONTO_CONSULTA + (1100 * R_PAGO.DIAS_MOROSIDAD);
                      
                    ELSIF R_PAGO.ID_ESPECIALIDAD = 500 THEN
                         V_MONTO_A_PAGAR := R_PAGO.MONTO_CONSULTA + (1900 * R_PAGO.DIAS_MOROSIDAD);
                         
                    ELSIF R_PAGO.ID_ESPECIALIDAD = 600 THEN
                         V_MONTO_A_PAGAR :=R_PAGO.MONTO_CONSULTA + (1700 * R_PAGO.DIAS_MOROSIDAD);
                   
                    ELSIF R_PAGO.ID_ESPECIALIDAD = 700 THEN
                         V_MONTO_A_PAGAR := R_PAGO.MONTO_CONSULTA + (1200 * R_PAGO.DIAS_MOROSIDAD);
                          
                    ELSIF R_PAGO.ID_ESPECIALIDAD = 800 THEN
                         V_MONTO_A_PAGAR := R_PAGO.MONTO_CONSULTA + (2000 * R_PAGO.DIAS_MOROSIDAD);
        
                        ELSE  
                        V_MONTO_A_PAGAR := R_PAGO.MONTO_CONSULTA + (2300 * R_PAGO.DIAS_MOROSIDAD);
                             
                    END IF;
        
        -- SE CALCULA LA EDAD PARA APLICAR AL MONTO FINAL EL DESCUENTO DE TERCERA EDAD    
                    
        V_EDAD:= FLOOR(MONTHS_BETWEEN(SYSDATE, R_PAGO.FECHA_NC)/12 ); 
    
        IF (V_EDAD>=60 and V_EDAD<=65) then  
        V_MONTO_A_PAGAR:= V_MONTO_A_PAGAR * 0.95;
        ELSIF (V_EDAD>=66 and V_EDAD<=70) then
        V_MONTO_A_PAGAR:= V_MONTO_A_PAGAR * 0.91;
        ELSIF (V_EDAD>=71 and V_EDAD<=76) then
        V_MONTO_A_PAGAR:= V_MONTO_A_PAGAR * 0.88;
        ELSIF (V_EDAD>=77 and V_EDAD<=85) then
        V_MONTO_A_PAGAR:= V_MONTO_A_PAGAR * 0.85;
        ELSIF (V_EDAD>=86 and V_EDAD<=100) then
        V_MONTO_A_PAGAR:= V_MONTO_A_PAGAR * 0.82;
        END IF; 
    
    -- SE INSERTA EN LA TABLA DE MOROSOS
    
     INSERT INTO PAGO_MOROSO 
     VALUES
     (R_PAGO.RUT,R_PAGO_RUTDV,R_PAGO.NOMBRE_COMPLETO,R_PAGO.ID_ATENCION,
     R_PAGO.FECHA_VENC,R_PAGO.FECHA_PAGO,R_PAGO.DIAS_MOROSIDAD,
     R_PAGO.NOMRE_ESP,R_PAGO.MONTO_CONSULTA,V_MONTO_A_PAGAR,'COBRO CON MULTA POR DIAS DE ATRASO EN EL PAGO');
     
   
    END IF;
    
  
  END LOOP;


    
    COMMIT;
    END obtener_pagos_pacientes;
   
END ;
    
    
   










